#!/bin/sh

# Readme settings
FILENAME="README.md"
BASE_FILENAME="readme-generator/BASE.md"

# Todo table settings
TODO_FORMATTER="readme-generator/format-todo"
TODO_HEADER="|Path|Line|Description|"
TODO_HEADER_SEP="|-|-|-|"

from_template() {
	rm -f "$FILENAME"
	cp "$BASE_FILENAME" "$FILENAME"
}

generate_lines_of_code(){
	echo "\n# Lines of code\n" >> "$FILENAME"
	scc -f html-table -s lines -x LICENSE --exclude-dir target >> "$FILENAME"
}

generate_todo() {
	script_name=$(basename "$0")

	echo "\n# Todo\n$TODO_HEADER\n$TODO_HEADER_SEP" >> "$FILENAME"
	grep -rn \
		--exclude "$script_name" \
		--exclude-dir .git \
		--exclude-dir target "TODO" . \
			| "$TODO_FORMATTER" \
			>> "$FILENAME"
}

main() {
	from_template
	generate_lines_of_code
	generate_todo
}

main
