#!/bin/sh

script_name=$(basename "$0")

# Todo table settings
TODO_HEADER="|Path|Line|Description|"
TODO_HEADER_SEP="|-|-|-|"

# Copy base README.md
rm -f README.md
cp BASE-README.md README.md

# Todos
echo "\n# Todo\n$TODO_HEADER\n$TODO_HEADER_SEP" >> README.md
grep -rn \
	--exclude "$script_name" \
	--exclude-dir .git \
	--exclude-dir target "TODO" . \
		| awk '
			{
				split($1, path, ":");
				printf "|";

				printf substr(path[1], 3, length(path[1]));
				printf "|";

				printf path[2];
				printf "|";

				$1=$2=$3="";
				printf $0;
				print "|";
			}
		' \
			>> README.md

# Lines of code
echo "\n# Lines of code\n" >> README.md
cloc --md  ./crates/* | tail -n +4 >> README.md
