#!/bin/sh

# Readme settings
FILENAME="README.md"
TEMPLATE_FILENAME="BASE-README.md"

# Todo table settings
TODO_HEADER="|Path|Line|Description|"
TODO_HEADER_SEP="|-|-|-|"

from_template() {
	rm -f "$FILENAME"
	cp "$TEMPLATE_FILENAME" "$FILENAME"
}

generate_lines_of_code(){
	echo "\n# Lines of code\n" >> "$FILENAME"
	scc -f html-table --exclude-dir target >> "$FILENAME"
}

generate_todo() {
	script_name=$(basename "$0")

	echo "\n# Todo\n$TODO_HEADER\n$TODO_HEADER_SEP" >> "$FILENAME"
	grep -rn \
		--exclude "$script_name" \
		--exclude-dir .git \
		--exclude-dir target "TODO" . \
			| awk '
				{
					split($1, path, ":");
					printf "|**";

					printf substr(path[1], 3, length(path[1]));
					printf "**|**";

					printf path[2];
					printf "**|**";

					$1=$2=$3="";
					gsub(/^[ \t]+/, "", $0)
					printf $0;
					print "**|";
				}
			' \
				>> "$FILENAME"
}

main() {
	from_template
	generate_lines_of_code
	generate_todo
}

main
