/// Application update messages.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub(crate) enum Message {
	CatppuccinFrappeTheme,
	CatppuccinLatteTheme,
	CatppuccinMacchiatoTheme,
	CatppuccinMochaTheme,
	DarkTheme,
	DefaultSettings,
	DraculaTheme,
	//Error(Error),
	GruvboxDarkTheme,
	GruvboxLightTheme,
	KanagawaDragonTheme,
	KanagawaLotusTheme,
	KanagawaWaveTheme,
	LightTheme,
	MoonflyTheme,
	NightflyTheme,
	None,
	NordTheme,
	SaveSettings,
	Scale(f32),
	Settings(crate::settings::Settings),
	SolarizedDarkTheme,
	SolarizedLightTheme,
	TokyoNightLightTheme,
	TokyoNightStormTheme,
	TokyoNightTheme,
	OxocarbonTheme,
	SettingsPage,
	StartPage,
	Exit,
}
